version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sikdorang-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: sikdorang-backend
    env_file:
      - ./apps/backend/.env
    ports:
      - '4000:4000'
    depends_on:
      - mysql
    restart: unless-stopped

  frontend-admin:
    build:
      context: .
      dockerfile: apps/frontend-admin/Dockerfile
    container_name: sikdorang-frontend-admin
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: unless-stopped

  frontend-menu-viewer:
    build:
      context: .
      dockerfile: apps/frontend-menu-viewer/Dockerfile
    container_name: sikdorang-frontend-menu-viewer
    ports:
      - '3001:3001'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
