import TopNav from '@/components/layout/Header/TopNav';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { MSWProvider } from './provider';
import '../styles/globals.css';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MSWProvider>
        <body className={`${pretendard.className} antialiased`}>
          <TopNav />
          {children}
        </body>
      </MSWProvider>
    </html>
  );
}
