export const ORDER_MENU_STATE = {
  MENU_UNAVAILABLE: 'MENU_UNAVAILABLE',
  OPTION_UNAVAILABLE: 'OPTION_UNAVAILABLE',
  AVAILABLE: 'AVAILABLE',
  SOLDOUT: 'SOLDOUT',
  PRICE_CHANGED: 'PRICE_CHANGED',
} as const;
